apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-$BRANCH
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        branch: $BRANCH
    spec:
      containers:
      - name: app
        image: miosaksregistry.azurecr.io/pyapp:$TAG
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: "miosaksregistry"
---
apiVersion: v1
kind: Service
metadata:
  name: app-$BRANCH
  labels:
    app: app
    branch: $BRANCH
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: app
    branch: $BRANCH
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-$BRANCH
  labels:
    app: app
    branch: $BRANCH
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "$BRANCH.k8s.monogra.fi"
    http:
      paths:
      - path: /
        backend:
          serviceName: app-$BRANCH
          servicePort: 80